#!/bin/sh

SRC=$(pwd)/src
DST=$(pwd)/dst
DRAFTS=$(pwd)/src/drafts
TEMPLATES=$(pwd)/templates
ENTRIES=$(pwd)/dst/entries
SITE="example.com"

[ -z "$EDITOR" ] && EDITOR=/usr/bin/nano

[ -f "$SRC" ] || mkdir -p "$SRC"
[ -f "$DST" ] || mkdir -p "$DST"
[ -f "$DRAFTS" ] || mkdir -p "$DRAFTS"
[ -f "$ENTRIES" ] || mkdir -p "$ENTRIES"
[ -f "$TEMPLATES" ] || mkdir -p "$TEMPLATES"

# Make a new blog entry
newpost () {
        filepath="$SRC/$1.md";
        if [ -f "$filepath" ]; then
                printf "$1 Already Exists!\n";
        else
                "$EDITOR" "$filepath";
                printf "add to (d)rafts/(r)emove/add to (e)ntry queue\n[d/r/e]: ";
                read -r choice;
                case "$choice" in 
                        d) mv "$filepath" "$DRAFTS"/"$1".md; printf "Added to drafts\n";;
                        e) printf "Added to src, ready to finalize\n" ;;
                        r) printf "Are you sure? [y/N]: ";
                           read -r c;
                           case "$c" in
                                   y|Y) rm "$filepath";;
                                   *) printf "Not Removed.\n";;
                           esac;;
                        *) printf "Invalid Option. added to queue\n";;
                esac
        fi
}
editpost() {
        filepath="$SRC/$1.md";
        if [ -f "$filepath" ]; then
                "$EDITOR" "$filepath";
        else
                printf "$1 Doesn't exist!\n"
        fi
}
# Edit existing drafts
editdrafts () {
        if [ -z "$1" ]; then
                printf "No draft selected.\nDrafts:\n"
                find "$DRAFTS" -type f -exec basename {} \; | cut -d'.' -f1
                printf "\nexample : esbu draft *Draft-Name*\n"
                exit
        else
                "$EDITOR" "$DRAFTS"/"$1".md
                printf "add the draft to entry queue? [y/N]: "
                read -r choice;
                case $choice in
                        y|Y) mv "$DRAFTS"/"$1".md "$SRC"/"$1".md
                           printf "moved draft to src.ready to finalize\n";;
                        n|N) printf "Draft remains.\n";;
                        *) printf "Invalid Option\n";;
                esac
        fi
}


# Get date from already published entry
getdate () {
        grep 'date-goes-here' "$1" | head -n1 | cut -c 28- | cut -c -13;
}

# Add index summary of posts
addsummary () {
        cat "$TEMPLATES"/index.html > "$DST"/index.html
        # Take 5 of the latest posts and order them from new to oldest.
        LATEST=$(find "$SRC" -maxdepth 1 -type f -name "*.md" -printf "\n%AD %AT %p" | tail -n +2 | sort -k1.8n -k1.1nr -k1 | cut -d' ' -f3 | sed -e "s/src/dst\/entries/g" -e "s/.md/.html/g" | tail -n5 )
        for t in $LATEST;
        do
                DATE=$(getdate "$t")
                filename=$(basename "$t")
                # Use the first markdown heading as the Title.
                TITLE=$(grep -m 1 "#" "$SRC"/"${filename%.html}".md | tr -d '#' )
                sed -i "/%ENTRIES%/a <li>$DATE -<a href='https://$SITE/entries/$filename'> $TITLE <\/a><\/li>\\n" "$DST"/index.html
        done
        sed -i "s/%ENTRIES%//" "$DST"/index.html;
        sed -i "s/%DATE%/$DATE/" "$DST"/index.html; 
}


# Create the "blogpage" which is a rolling view of blog posts.
blogpage () {
        cat "$TEMPLATES"/blogpage.html > "$DST"/blogpage.html;
        # Take all of the latest posts and order them from new to oldest.
        LATEST=$(find "$SRC" -maxdepth 1 -name "*.md" -type f -printf "\n%AD %AT %p" | tail -n +2 | sort -k1.8n -k1.1nr -k1 | cut -d' ' -f3 | sed -e "s/src/dst\/entries/g" -e "s/.md/.html/g")
        for t in $LATEST;
        do
                DATE=$(getdate "$t") # Set the date
                filename=$(basename "$t");
                # Use the first markdown heading as the Title.
                TITLE=$(grep -m 1 "#" "$SRC"/"${filename%.html}".md | tr -d '#' )
                sed -i "/%ENTRIES%/a <li><a href='https://$SITE/entries/$filename'>$DATE : $TITLE <\/a><\/li>\\n" "$DST"/blogpage.html; 
        done
        sed -i "s/%ENTRIES%//" "$DST"/blogpage.html;
}

# Adds a blog post to rss.xml
additem () {
        # Checks if entry with the same name already exists, if so, it uses the Date in the existing entry
        # as DATE, otherwise it uses current date.
        if [ -f "$ENTRIES"/"${2%.md}".html ]; then
                DATE=$(grep 'date-goes-here' "$ENTRIES"/"${2%.md}".html | head -n1 | cut -c 28- | cut -c -13)
        else
                DATE=$(date -R)
        fi

        TITLE=$(grep -m 1 "#" "$1" | tr -d '#' ); # Use the first heading as the Title.

        cat "$TEMPLATES"/item.xml >> "$DST"/rss.xml;
        sed -i -e "s:%NAME%:$NAME:" \
            -e "s/%URL%/entries\/${2%.md}.html/" \
            -e "s/%DATE%/$DATE/" -e "s/%CONTENT%]]><\/description>//" "$DST"/rss.xml;

        cat "$3" >> "$DST"/rss.xml;
        sed -i -e 's/\/> <!---height=//g' \
            -e 's/H--->/\/>/g' "$DST"/rss.xml;

        echo "]]></description>" >> "$DST"/rss.xml;
        echo "</item>" >> "$DST"/rss.xml;
}

# Make new individual entry
makepage () { 
        DATE=$(date -R); # use current date as DATE
        NAME=$(grep "#" "$SRC"/"$1" | head -n1 | cut -c 3-) # use the first heading as Title

        sed "/%CONTENT%/r $2" "$TEMPLATES"/entry.html \
                | sed -e 's/%CONTENT%//' \
                        -e "s/%DATE%/<!--date-goes-here-$DATE-->/" \
                        -e "s:%TITLE%:$NAME:" \
                        > "$ENTRIES"/"${1%.md}".html
}

# Take all markdown files in src/ (excluding drafts) and create corresponding html files in entries/,
# also creates/updates rss feed , blogpage and index.html
finalize () {
        head -n -3 "$TEMPLATES"/rss.xml > "$DST"/rss.xml # initialize rss.xml to add items to later

        FILES=$(find "$SRC" -maxdepth 1 -name "*.md" -type f -printf "\n%AD %AT %p" | tail -n +2 | sort -k1.8n -k1.1nr -k1 | cut -d' ' -f3) # sort .md files by time from oldest to newest.
        for entry in $FILES;
        do
                file=$(basename "$entry");
                RAWHTML=$ENTRIES/${file%.md}-tmp.html;
               
                markdown -f fencedcode "$entry" | \
                        sed -e 's/\/> <!---height=/ style="width:100%;height:auto;max-width:/g' \
                            -e 's/px--->/px" \/>/g' > "$RAWHTML";
               
                [ -f "$ENTRIES"/"${file%.md}".html ] || makepage "$file" "$RAWHTML";
                additem "$entry" "$file" "$RAWHTML" # Add entry to rss.xml 
                [ -f "$RAWHTML" ] && rm "$RAWHTML" 
        done

        echo "</channel>" >> "$DST"/rss.xml
        echo "</rss>" >> "$DST"/rss.xml
        addsummary;
        blogpage;
}

case $1 in
        n|new)    newpost "$2";; # Create a new markdown entry
        e|edit)    editpost "$2";; # Create a new markdown entry
        l|list)   printf "List of entries:\n"
                find "$SRC" -maxdepth 1 -type f -exec basename {} \; | cut -d'.' -f1;;
        s|summary) addsummary;;
        d|draft)  editdrafts "$2";;
        r|remove) rm "$ENTRIES"/"$2".html
                rm "$SRC"/"$2".md \
                        && printf "Removed %s from entries\n" "$2" \
                        || printf "\n%s doesn't exist\n" "$2";;
        f|finalize) finalize;;
        *)      printf "esbu OPTION arg1 [arg2]\n"
                printf "OPTIONS:\n"
                printf "\tn, new - create new blog post\n"
                printf "\te, edit - edit already existing blog posts\n"
                printf "\tl, list - list all blog entries\n"
                printf "\ts, summary - make index.html\n"
                printf "\td, draft - edit drafts\n"
                printf "\tf, finalize - finalize blog - ready to deploy\n"
                printf "\tr, remove - remove a given entry name\n"
                printf "EXAMPLES:\n"
                printf "\tesbu new newpost  => creates a new entry as newpost.md\n"
                printf "\tesbu list =>  lists all entries\n"
                printf "\tesbu r newpost => removes newpost\n";;
esac
exit $?
